/* Generated by Together */

package msg.format;

import java.util.*;
import owch.*;
import java.io.*; 
public class SerialFormat implements Format {
    public void read(InputStream i,Map m)throws IOException{

	ObjectInput  is = new ObjectInputStream(i);
	try{
	    Map m1=(Map)is.readObject(); 
	    m1.putAll(m);
	    Env.debug(500,"** Serial"+m1.toString());
	}catch(Exception e){
	    Env.debug(5,"** malformed XMLFormat Notification");
	}
	

    }

    public void write(OutputStream o, Map m)throws IOException{  
	ByteArrayOutputStream  bo=new ByteArrayOutputStream(); 
	ObjectOutput  os = new ObjectOutputStream(bo);
	os.writeObject(m);  
	os.close();
	bo.close();
	o.write(bo.toByteArray());
	o.flush();
    }
}
