/* Generated by Together */

package msg.format;

import owch.*;
import java.io.*;

import java.util.*;

public class XMLSerialFormat implements Format {
    public void read(InputStream i,Map m)throws IOException{
	try{
	    ObjectInput  is = (ObjectInput)Class.forName("archiver.XMLInputStream").getConstructor(new Class[]{i.getClass()}).newInstance(new Object[]{i});

	    Map m1=(Map)is.readObject(); 
	    m1.putAll(m);
	}catch(Exception e){
	    Env.debug(5,"** malformed XMLFormat Notification");
	}

    }

    public void write(OutputStream o, Map m)throws IOException{  
	try{
	    ByteArrayOutputStream  bo=new ByteArrayOutputStream(); 
	    ObjectOutput  os = (ObjectOutput)Class.forName("archiver.XMLOutputStream").getConstructor(new Class[]{o.getClass()}).newInstance(new Object[]{o});
	    os.writeObject(m);  
	    os.close();
	    bo.close();
	    o.write(bo.toByteArray());
	    o.flush();	}catch(Exception e){
		Env.debug(5,"** malformed XMLFormat Notification");
	    }
    }
}
