/* Generated by Together */

package net.sourceforge.idyuts.IOPipes.SQLToken;

import net.sourceforge.idyuts.IOPipes.*;

public class FROM extends SQLClauseImpl {
    public void recv(Object[] s) {
        synchronized (stage) {
            stage = f_loop(s, " FROM ", ", ");
            xmit();
        }
    }
}


