/* Generated by Together */

package net.sourceforge.nlp;

public class Report {
    private Occurence occ;
    private String text;

    public Report(String t, Occurence o) {
        occ = o;
        text = t;
    }

    public String toString() {
        return text + "=" + occ.getCount();
    }

}




