/* Generated by Together */

package net.sourceforge.nlp;

import java.util.HashMap;
import java.util.Map;

public class VerbKnowledge {
    protected Map<String, String> metaClause = new HashMap<String, String>(96);
    protected Map<String, Object[]> clauseVerb = new HashMap<String, Object[]>(96);
}




