/* Generated by Together */

package net.sourceforge.nlp;

import java.util.*;

public class VerbKnowledge {
    protected Map metaClause = new HashMap(96);
    protected Map clauseVerb = new HashMap(96);
}




