
all:
	sh genClass.sh Bool boolean
	sh genClass.sh Integer Integer 
	sh genClass.sh String String 
	sh genClass.sh Stream java.io.InputStream 
	sh genClass.sh Reader java.io.Reader 
	sh genClass.sh Writer java.io.Writer 
	sh genClass.sh Object  'Object'
	sh genClass.sh Array  'Object[]'
	sh genClass.sh Matrix  'Object[][]'
	sh genClass.sh Collection java.util.Collection
	sh genClass.sh Map    java.util.Map
	sh genClass.sh MapArray   "java.util.Map[]" 
	sh genClass.sh floatArray 	float[] 
	sh genClass.sh float		float
	sh genClass.sh intArray 	int[] 
	sh genClass.sh int		int    
	sh genClass.sh Number		Number    
	sh genClass.sh Graphics		java.awt.Graphics    
	sh genClass.sh StreamTokenizer	java.io.StreamTokenizer
	sh genClass.sh DatagramPacket	java.net.DatagramPacket
	
