/* Generated by Together */

package net.sourceforge.idyuts.IOPipes.functor;

import net.sourceforge.idyuts.IOPipes.*;

public class xlateTranslateIntoHistoricalAttribute extends StringFunctorImpl {
    public String fire(String s) {
        return s;
    };

    /*deprecated*/
}


