/* Generated by Together */

package net.sourceforge.idyuts.IOPipes.functor;

import net.sourceforge.idyuts.IOPipes.*;

import java.util.*;

public class xlateFirstDotToken extends StringFunctorImpl {
    /** xlate function used to grab the tablename from col0 */
    public String fire(String s) {
        StringTokenizer st = new StringTokenizer(s, ".");
        if (st.hasMoreTokens()) {
            return st.nextToken();
        }
        return s;
    };
}


